language: python
python:
- 3.8
# Cache Dependencies
cache: pip
branches:
  only:
  - master
# install dependencies
before_install:
  - git submodule update --init --recursive
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pelican-themes -vi ./clepyd-theme

before_script:
  - invoke --list
script:
  - invoke publish-carefully

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master